# Generated by Django 3.0.2 on 2020-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
